### Employees details with OOP

In [65]:
class Employee():
    def __init__(self, name, number, address, salary, post, year_of_joining, education, year_of_experience):
        self.name = name
        self.number = number
        self.address = address
        self.salary = salary
        self.post = post
        self.year_of_joining = year_of_joining
        self.education = education
        self.year_of_experience = year_of_experience
    def describe_employee(self):
        print("\n")
        print(f"Name : {self.name}")
        print(f"Number : {self.number}")
        print(f"Address : {self.address}")
        print(f"Salary : {self.salary}")
        print(f"Post : {self.post}")
        print(f"Year of joining : {self.year_of_joining}")
        print(f"Education : {self.education}")
        print(f"Year of experience : {self.year_of_experience}")
        print("\n")
    def update_year_of_experience(self, new_experience):
        self.year_of_experience = new_experience
        print(f"Updated year of experience to : {new_experience}")
    def increase_salary(self, increment):
        self.salary += increment
        print(f"New salary after increment : {self.salary}")
employee101 = Employee("Salar", 234, "Karachi", 120000, "Assistant Manager", 2021, 'BSCS', 2)
print(employee101.name)
print(employee101.address)
print(employee101.salary)
print(employee101.post)
employee101.describe_employee()
employee101.update_year_of_experience(3)
employee101.increase_salary(5000)
employees = [
    Employee("Sara", 200, "Lhr", 60000, "HR", 2023, "BS", 1),
    Employee("Haris", 201, 'Isb', 30000, 'Assistant', 2024, 'Graduation', 0),
    Employee("Hina", 202, 'Khi', 90000, 'Supervisor', 2022, 'BSIT', 2),
    Employee("Salman", 203, 'Pindi', 150000, 'Manager', 2020, 'BBA', 4),
    Employee("Rehan", 204, 'Haripur', 200000, 'Branch Manager', 2019, 'MBA', 5),
    Employee("Noman", 205, 'Hunza', 80000, 'AM', 2021, 'BE', 3),
    Employee("Maham", 206, 'Multan', 50000, 'Admin', 2023, 'BSCS', 1),
    Employee("Fiza", 207, 'Bakhar', 750000, 'Operation Manager', 2021, 'BBA', 3),
    Employee("Hashir", 208, 'Gawadar', 60000, 'Sales', 2022, 'BSc', 2),
    Employee("Daniyal", 209, 'Quetta', 30000, 'Internee', 2024, 'BSDS', 0)
]
employee_details_list = [employee.describe_employee() for employee in employees]
employees[4].update_year_of_experience(3)
employees[5].increase_salary(7000)
employees[2].update_year_of_experience(1)
employees[3].increase_salary(5000)

Salar
Karachi
120000
Assistant Manager


Name : Salar
Number : 234
Address : Karachi
Salary : 120000
Post : Assistant Manager
Year of joining : 2021
Education : BSCS
Year of experience : 2


Updated year of experience to : 3
New salary after increment : 125000


Name : Sara
Number : 200
Address : Lhr
Salary : 60000
Post : HR
Year of joining : 2023
Education : BS
Year of experience : 1




Name : Haris
Number : 201
Address : Isb
Salary : 30000
Post : Assistant
Year of joining : 2024
Education : Graduation
Year of experience : 0




Name : Hina
Number : 202
Address : Khi
Salary : 90000
Post : Supervisor
Year of joining : 2022
Education : BSIT
Year of experience : 2




Name : Salman
Number : 203
Address : Pindi
Salary : 150000
Post : Manager
Year of joining : 2020
Education : BBA
Year of experience : 4




Name : Rehan
Number : 204
Address : Haripur
Salary : 200000
Post : Branch Manager
Year of joining : 2019
Education : MBA
Year of experience : 5




Name : Noman
Number : 205
Address : Hunza
Salary : 80000
Post : AM
Year of joining : 2021
Education : BE
Year of experience : 3




Name : Maham
Number : 206
Address : Multan
Salary : 50000
Post : Admin
Year of joining : 2023
Education : BSCS
Year of experience : 1




Name : Fiza
Number : 207
Address : Bakhar
Salary : 750000
Post : Operation Manager
Year of joining : 2021
Education : BBA
Year of experience : 3




Name : Hashir
Number : 208
Address : Gawadar
Salary : 60000
Post : Sales
Year of joining : 2022
Education : BSc
Year of experience : 2




Name : Daniyal
Number : 209
Address : Quetta
Salary : 30000
Post : Internee
Year of joining : 2024
Education : BSDS
Year of experience : 0


Updated year of experience to : 3
New salary after increment : 87000
Updated year of experience to : 1
New salary after increment : 155000

### Employees details without OOP

In [13]:
def describe_employee(employee):
    print("\n")
    print(f"Name : {employee['name']}")
    print(f"Number : {employee['number']}")
    print(f"Address : {employee['address']}")
    print(f"Salary : {employee['salary']}")
    print(f"Post : {employee['post']}")
    print(f"Year of joining : {employee['year_of_joining']}")
    print(f"Education : {employee['education']}")
    print(f"Year of experience : {employee['year_of_experience']}")
def update_year_of_experience(employee, new_experience):
    employee['year_of_experience'] = new_experience
    print(f"updated year of experience to : {new_experience}")
def increase_salary(employee, increment):
    employee['salary'] += increment
    print(f"New salary after increment : {employee['salary']}")
employee101 = {
    'name' : 'Sara',
    'number': 234,
    'address': 'Karachi',
    'salary': 100000,
    'post': 'AM',
    'year_of_joining': 2023,
    'education': 'BSCS',
    'year_of_experience': 1
}
print(employee101['name'])
print(employee101['address'])
print(employee101['post'])
print(employee101['education'])
employees = [
    {'name':"Sara", 'number': 200, 'address': "Lhr", 'salary': 60000, 'post': "HR", 'year_of_joining': 2023, 'education': "BS", 'year_of_experience': 1},
    {'name':"Haris", 'number': 201, 'address': 'Isb', 'salary': 30000, 'post': 'Assistant', 'year_of_joining': 2024, 'education': 'Graduation', 'year_of_experience': 0},
    {'name':"Hina", 'number': 202, 'address': 'Khi', 'salary': 90000, 'post': 'Supervisor', 'year_of_joining': 2022, 'education': 'BSIT', 'year_of_experience': 2},
    {'name':"Salman", 'number': 203, 'address': 'Pindi', 'salary': 150000, 'post': 'Manager', 'year_of_joining': 2020, 'education': 'BBA', 'year_of_experience': 4},
    {'name':"Rehan", 'number': 204, 'address': 'Haripur', 'salary': 200000, 'post': 'Branch Manager', 'year_of_joining': 2019, 'education':'MBA', 'year_of_experience': 5},
    {'name':"Noman", 'number': 205, 'address': 'Hunza', 'salary': 80000, 'post': 'AM', 'year_of_joining': 2021, 'education': 'BE', 'year_of_experience': 3},
    {'name':"Maham", 'number': 206, 'address': 'Multan', 'salary': 50000, 'post': 'Admin', 'year_of_joining': 2023, 'education': 'BSCS', 'year_of_experience': 1},
    {'name':"Fiza", 'number': 207, 'address': 'Bakhar', 'salary': 750000, 'post': 'Operation Manager', 'year_of_joining': 2021, 'education': 'BBA', 'year_of_experience': 3},
    {'name':"Hashir", 'number': 208, 'address': 'Gawadar', 'salary': 60000, 'post': 'Sales', 'year_of_joining': 2022, 'education': 'BSc', 'year_of_experience': 2},
    {'name':"Daniyal", 'number': 209, 'address': 'Quetta', 'salary': 30000, 'post': 'Internee', 'year_of_joining': 2024, 'education': 'BSDS', 'year_of_experience': 0}
]
for employee in employees:
    describe_employee(employee)
print("\n")
update_year_of_experience(employees[3], 5)
increase_salary(employees[1], 5000)

Sara
Karachi
AM
BSCS


Name : Sara
Number : 200
Address : Lhr
Salary : 60000
Post : HR
Year of joining : 2023
Education : BS
Year of experience : 1


Name : Haris
Number : 201
Address : Isb
Salary : 30000
Post : Assistant
Year of joining : 2024
Education : Graduation
Year of experience : 0


Name : Hina
Number : 202
Address : Khi
Salary : 90000
Post : Supervisor
Year of joining : 2022
Education : BSIT
Year of experience : 2


Name : Salman
Number : 203
Address : Pindi
Salary : 150000
Post : Manager
Year of joining : 2020
Education : BBA
Year of experience : 4


Name : Rehan
Number : 204
Address : Haripur
Salary : 200000
Post : Branch Manager
Year of joining : 2019
Education : MBA
Year of experience : 5


Name : Noman
Number : 205
Address : Hunza
Salary : 80000
Post : AM
Year of joining : 2021
Education : BE
Year of experience : 3


Name : Maham
Number : 206
Address : Multan
Salary : 50000
Post : Admin
Year of joining : 2023
Education : BSCS
Year of experience : 1


Name : Fiza
Number : 207
Address : Bakhar
Salary : 750000
Post : Operation Manager
Year of joining : 2021
Education : BBA
Year of experience : 3


Name : Hashir
Number : 208
Address : Gawadar
Salary : 60000
Post : Sales
Year of joining : 2022
Education : BSc
Year of experience : 2


Name : Daniyal
Number : 209
Address : Quetta
Salary : 30000
Post : Internee
Year of joining : 2024
Education : BSDS
Year of experience : 0


updated year of experience to : 5
New salary after increment : 35000